version: '3.9'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: database
    container_name: database
    volumes:
      - ./_database:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123.
    ports:
      - "11433:1433"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "10080:80"
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"